import './globals.css'
import {useRouter} from "next/navigation"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self'; font-src 'self' cdn.example.com; connect-src xcwxpqdymboeuchzyzbh.supabase.co localhost:3000 fullstackfinal.vercel.app;" />
  <body>
        <main className="min-h-screen flex flex-col items-center" style={{backgroundColor: '#0a0a0a'}}>
          {children}
        </main>
      </body>
    </html>
  )
}
